# Leaflet Tiny Log Collector configuration
tlc:

  # Base configuration parameters
  system:

    # Try to reconnect a disconnected log stream after milliseconds
    reconnection-poll-rate: 1000

    # Enables trimming the stdout header of the Docker Engine log stream (first 8 bytes are removed, if enabled).
    # Should be enabled on Linux systems.
    enable-trimming-stdout-header: true

  # Configuration of external services
  connection:

    # Docker Engine API connection parameters
    docker:

      # Connection type: specify 'socket' (to connect via UNIX socket) or 'tcp' (to connect via HTTP)
      type: socket

      # Target endpoint (make sure to specify it accordingly to the selected connection type)
      uri: /var/run/docker.sock

    # Tiny Log Processor API connection parameters
    tlp:

      # Target endpoint
      uri: http://localhost:8084/tlp

  # Pipeline configurations
  # -- example --
  # - log-stream-name: my-log-stream  # (arbitrary)
  #   listener-type: docker           # (docker = will read logs from a Docker log stream; currently only Docker is supported)
  #   listener-config:                # configuration for the specified listener
  #     container-name: my-container  # Docker specific configuration, name of the container to listen logs of
  #   parsers:                        # parsers to handle the log stream, order of the specified parsers matter
  #     - byte-array                  # parses the log messages from a byte array into a string
  #     - joining-json                # joins the pieces of strings into a JSON document
  #   mapper-type: identity           # data structure mapper, can be
  #                                   #  - identity (no change)
  #                                   #  - logstash-to-tlp (Logstash-like logs to TLP log request),
  #                                   #  - custom-to-tlp (custom log structure to TLP log request)
  #   mapper-config:                  # optional mapping configuration when custom-to-tlp mapping is selected
  #     level: $.level                #  - it is a key-value map, where the keys are the keys of TLPLogMessage and ErrorLog interfaces,
  #     content: $.message            #    and the values are JSON path expressions referencing the fields of the log
  #     timeStamp: $.date             #    message structure to be mapped
  #     [ ... ]
  #   publishers:                     # publisher submit the logs for further processing
  #     - console                     # displays the collected log messages on the console (only recommended for debugging purposes)
  #   enabled: true                   # optional flag to explicitly enable/disable this pipeline (defaults to true)
  pipelines: []
